// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServeMetricsParams creates a new ServeMetricsParams object
// with the default values initialized.
func NewServeMetricsParams() *ServeMetricsParams {
	var ()
	return &ServeMetricsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServeMetricsParamsWithTimeout creates a new ServeMetricsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServeMetricsParamsWithTimeout(timeout time.Duration) *ServeMetricsParams {
	var ()
	return &ServeMetricsParams{

		timeout: timeout,
	}
}

// NewServeMetricsParamsWithContext creates a new ServeMetricsParams object
// with the default values initialized, and the ability to set a context for a request
func NewServeMetricsParamsWithContext(ctx context.Context) *ServeMetricsParams {
	var ()
	return &ServeMetricsParams{

		Context: ctx,
	}
}

// NewServeMetricsParamsWithHTTPClient creates a new ServeMetricsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServeMetricsParamsWithHTTPClient(client *http.Client) *ServeMetricsParams {
	var ()
	return &ServeMetricsParams{
		HTTPClient: client,
	}
}

/*ServeMetricsParams contains all the parameters to send to the API endpoint
for the serve metrics operation typically these are written to a http.Request
*/
type ServeMetricsParams struct {

	/*Fields*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the serve metrics params
func (o *ServeMetricsParams) WithTimeout(timeout time.Duration) *ServeMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the serve metrics params
func (o *ServeMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the serve metrics params
func (o *ServeMetricsParams) WithContext(ctx context.Context) *ServeMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the serve metrics params
func (o *ServeMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the serve metrics params
func (o *ServeMetricsParams) WithHTTPClient(client *http.Client) *ServeMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the serve metrics params
func (o *ServeMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the serve metrics params
func (o *ServeMetricsParams) WithFields(fields *string) *ServeMetricsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the serve metrics params
func (o *ServeMetricsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *ServeMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
