// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cldmnky/teamcity-rest-client-go/models"
)

// ServeMetricsReader is a Reader for the ServeMetrics structure.
type ServeMetricsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServeMetricsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServeMetricsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServeMetricsOK creates a ServeMetricsOK with default headers values
func NewServeMetricsOK() *ServeMetricsOK {
	return &ServeMetricsOK{}
}

/*ServeMetricsOK handles this case with default header values.

successful operation
*/
type ServeMetricsOK struct {
	Payload *models.Metrics
}

func (o *ServeMetricsOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/server/metrics][%d] serveMetricsOK  %+v", 200, o.Payload)
}

func (o *ServeMetricsOK) GetPayload() *models.Metrics {
	return o.Payload
}

func (o *ServeMetricsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Metrics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
