// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTokenReader is a Reader for the DeleteToken structure.
type DeleteTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteTokenDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteTokenDefault creates a DeleteTokenDefault with default headers values
func NewDeleteTokenDefault(code int) *DeleteTokenDefault {
	return &DeleteTokenDefault{
		_statusCode: code,
	}
}

/*DeleteTokenDefault handles this case with default header values.

successful operation
*/
type DeleteTokenDefault struct {
	_statusCode int
}

// Code gets the status code for the delete token default response
func (o *DeleteTokenDefault) Code() int {
	return o._statusCode
}

func (o *DeleteTokenDefault) Error() string {
	return fmt.Sprintf("[DELETE /app/rest/users/{userLocator}/tokens/{name}][%d] deleteToken default ", o._statusCode)
}

func (o *DeleteTokenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
