// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTokensParams creates a new GetTokensParams object
// with the default values initialized.
func NewGetTokensParams() *GetTokensParams {
	var ()
	return &GetTokensParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTokensParamsWithTimeout creates a new GetTokensParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTokensParamsWithTimeout(timeout time.Duration) *GetTokensParams {
	var ()
	return &GetTokensParams{

		timeout: timeout,
	}
}

// NewGetTokensParamsWithContext creates a new GetTokensParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTokensParamsWithContext(ctx context.Context) *GetTokensParams {
	var ()
	return &GetTokensParams{

		Context: ctx,
	}
}

// NewGetTokensParamsWithHTTPClient creates a new GetTokensParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTokensParamsWithHTTPClient(client *http.Client) *GetTokensParams {
	var ()
	return &GetTokensParams{
		HTTPClient: client,
	}
}

/*GetTokensParams contains all the parameters to send to the API endpoint
for the get tokens operation typically these are written to a http.Request
*/
type GetTokensParams struct {

	/*Fields*/
	Fields *string
	/*UserLocator*/
	UserLocator string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tokens params
func (o *GetTokensParams) WithTimeout(timeout time.Duration) *GetTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tokens params
func (o *GetTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tokens params
func (o *GetTokensParams) WithContext(ctx context.Context) *GetTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tokens params
func (o *GetTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tokens params
func (o *GetTokensParams) WithHTTPClient(client *http.Client) *GetTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tokens params
func (o *GetTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get tokens params
func (o *GetTokensParams) WithFields(fields *string) *GetTokensParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get tokens params
func (o *GetTokensParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserLocator adds the userLocator to the get tokens params
func (o *GetTokensParams) WithUserLocator(userLocator string) *GetTokensParams {
	o.SetUserLocator(userLocator)
	return o
}

// SetUserLocator adds the userLocator to the get tokens params
func (o *GetTokensParams) SetUserLocator(userLocator string) {
	o.UserLocator = userLocator
}

// WriteToRequest writes these params to a swagger request
func (o *GetTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param userLocator
	if err := r.SetPathParam("userLocator", o.UserLocator); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
