// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cldmnky/teamcity-rest-client-go/models"
)

// GetTokensReader is a Reader for the GetTokens structure.
type GetTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTokensOK creates a GetTokensOK with default headers values
func NewGetTokensOK() *GetTokensOK {
	return &GetTokensOK{}
}

/*GetTokensOK handles this case with default header values.

successful operation
*/
type GetTokensOK struct {
	Payload *models.Tokens
}

func (o *GetTokensOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/users/{userLocator}/tokens][%d] getTokensOK  %+v", 200, o.Payload)
}

func (o *GetTokensOK) GetPayload() *models.Tokens {
	return o.Payload
}

func (o *GetTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tokens)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
