// Code generated by go-swagger; DO NOT EDIT.

package cloud_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServeProfilesParams creates a new ServeProfilesParams object
// with the default values initialized.
func NewServeProfilesParams() *ServeProfilesParams {
	var ()
	return &ServeProfilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServeProfilesParamsWithTimeout creates a new ServeProfilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServeProfilesParamsWithTimeout(timeout time.Duration) *ServeProfilesParams {
	var ()
	return &ServeProfilesParams{

		timeout: timeout,
	}
}

// NewServeProfilesParamsWithContext creates a new ServeProfilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewServeProfilesParamsWithContext(ctx context.Context) *ServeProfilesParams {
	var ()
	return &ServeProfilesParams{

		Context: ctx,
	}
}

// NewServeProfilesParamsWithHTTPClient creates a new ServeProfilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServeProfilesParamsWithHTTPClient(client *http.Client) *ServeProfilesParams {
	var ()
	return &ServeProfilesParams{
		HTTPClient: client,
	}
}

/*ServeProfilesParams contains all the parameters to send to the API endpoint
for the serve profiles operation typically these are written to a http.Request
*/
type ServeProfilesParams struct {

	/*Fields*/
	Fields *string
	/*Locator*/
	Locator *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the serve profiles params
func (o *ServeProfilesParams) WithTimeout(timeout time.Duration) *ServeProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the serve profiles params
func (o *ServeProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the serve profiles params
func (o *ServeProfilesParams) WithContext(ctx context.Context) *ServeProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the serve profiles params
func (o *ServeProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the serve profiles params
func (o *ServeProfilesParams) WithHTTPClient(client *http.Client) *ServeProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the serve profiles params
func (o *ServeProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the serve profiles params
func (o *ServeProfilesParams) WithFields(fields *string) *ServeProfilesParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the serve profiles params
func (o *ServeProfilesParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithLocator adds the locator to the serve profiles params
func (o *ServeProfilesParams) WithLocator(locator *string) *ServeProfilesParams {
	o.SetLocator(locator)
	return o
}

// SetLocator adds the locator to the serve profiles params
func (o *ServeProfilesParams) SetLocator(locator *string) {
	o.Locator = locator
}

// WriteToRequest writes these params to a swagger request
func (o *ServeProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Locator != nil {

		// query param locator
		var qrLocator string
		if o.Locator != nil {
			qrLocator = *o.Locator
		}
		qLocator := qrLocator
		if qLocator != "" {
			if err := r.SetQueryParam("locator", qLocator); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
