// Code generated by go-swagger; DO NOT EDIT.

package cloud_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cldmnky/teamcity-rest-client-go/models"
)

// ServeProfilesReader is a Reader for the ServeProfiles structure.
type ServeProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServeProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServeProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServeProfilesOK creates a ServeProfilesOK with default headers values
func NewServeProfilesOK() *ServeProfilesOK {
	return &ServeProfilesOK{}
}

/*ServeProfilesOK handles this case with default header values.

successful operation
*/
type ServeProfilesOK struct {
	Payload *models.CloudProfiles
}

func (o *ServeProfilesOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/cloud/profiles][%d] serveProfilesOK  %+v", 200, o.Payload)
}

func (o *ServeProfilesOK) GetPayload() *models.CloudProfiles {
	return o.Payload
}

func (o *ServeProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudProfiles)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
