// Code generated by go-swagger; DO NOT EDIT.

package cloud_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cldmnky/teamcity-rest-client-go/models"
)

// ServeImageReader is a Reader for the ServeImage structure.
type ServeImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServeImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServeImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServeImageOK creates a ServeImageOK with default headers values
func NewServeImageOK() *ServeImageOK {
	return &ServeImageOK{}
}

/*ServeImageOK handles this case with default header values.

successful operation
*/
type ServeImageOK struct {
	Payload *models.CloudImage
}

func (o *ServeImageOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/cloud/images/{imageLocator}][%d] serveImageOK  %+v", 200, o.Payload)
}

func (o *ServeImageOK) GetPayload() *models.CloudImage {
	return o.Payload
}

func (o *ServeImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudImage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
