// Code generated by go-swagger; DO NOT EDIT.

package cloud_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cldmnky/teamcity-rest-client-go/models"
)

// ServeProfileReader is a Reader for the ServeProfile structure.
type ServeProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServeProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServeProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServeProfileOK creates a ServeProfileOK with default headers values
func NewServeProfileOK() *ServeProfileOK {
	return &ServeProfileOK{}
}

/*ServeProfileOK handles this case with default header values.

successful operation
*/
type ServeProfileOK struct {
	Payload *models.CloudProfile
}

func (o *ServeProfileOK) Error() string {
	return fmt.Sprintf("[GET /app/rest/cloud/profiles/{profileLocator}][%d] serveProfileOK  %+v", 200, o.Payload)
}

func (o *ServeProfileOK) GetPayload() *models.CloudProfile {
	return o.Payload
}

func (o *ServeProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
