// Code generated by go-swagger; DO NOT EDIT.

package investigation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new investigation API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for investigation API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetInvestigations(params *GetInvestigationsParams, authInfo runtime.ClientAuthInfoWriter) (*GetInvestigationsOK, error)

	ReplaceInstance(params *ReplaceInstanceParams, authInfo runtime.ClientAuthInfoWriter) (*ReplaceInstanceOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetInvestigations get investigations API
*/
func (a *Client) GetInvestigations(params *GetInvestigationsParams, authInfo runtime.ClientAuthInfoWriter) (*GetInvestigationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetInvestigationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getInvestigations",
		Method:             "GET",
		PathPattern:        "/app/rest/investigations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetInvestigationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetInvestigationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getInvestigations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ReplaceInstance replace instance API
*/
func (a *Client) ReplaceInstance(params *ReplaceInstanceParams, authInfo runtime.ClientAuthInfoWriter) (*ReplaceInstanceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReplaceInstanceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "replaceInstance",
		Method:             "PUT",
		PathPattern:        "/app/rest/investigations/{investigationLocator}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ReplaceInstanceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReplaceInstanceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for replaceInstance: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
