// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRequestFinalizationParams creates a new RequestFinalizationParams object
// with the default values initialized.
func NewRequestFinalizationParams() *RequestFinalizationParams {

	return &RequestFinalizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestFinalizationParamsWithTimeout creates a new RequestFinalizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestFinalizationParamsWithTimeout(timeout time.Duration) *RequestFinalizationParams {

	return &RequestFinalizationParams{

		timeout: timeout,
	}
}

// NewRequestFinalizationParamsWithContext creates a new RequestFinalizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestFinalizationParamsWithContext(ctx context.Context) *RequestFinalizationParams {

	return &RequestFinalizationParams{

		Context: ctx,
	}
}

// NewRequestFinalizationParamsWithHTTPClient creates a new RequestFinalizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestFinalizationParamsWithHTTPClient(client *http.Client) *RequestFinalizationParams {

	return &RequestFinalizationParams{
		HTTPClient: client,
	}
}

/*RequestFinalizationParams contains all the parameters to send to the API endpoint
for the request finalization operation typically these are written to a http.Request
*/
type RequestFinalizationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request finalization params
func (o *RequestFinalizationParams) WithTimeout(timeout time.Duration) *RequestFinalizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request finalization params
func (o *RequestFinalizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request finalization params
func (o *RequestFinalizationParams) WithContext(ctx context.Context) *RequestFinalizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request finalization params
func (o *RequestFinalizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request finalization params
func (o *RequestFinalizationParams) WithHTTPClient(client *http.Client) *RequestFinalizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request finalization params
func (o *RequestFinalizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RequestFinalizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
