// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RequestGcReader is a Reader for the RequestGc structure.
type RequestGcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestGcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewRequestGcDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewRequestGcDefault creates a RequestGcDefault with default headers values
func NewRequestGcDefault(code int) *RequestGcDefault {
	return &RequestGcDefault{
		_statusCode: code,
	}
}

/*RequestGcDefault handles this case with default header values.

successful operation
*/
type RequestGcDefault struct {
	_statusCode int
}

// Code gets the status code for the request gc default response
func (o *RequestGcDefault) Code() int {
	return o._statusCode
}

func (o *RequestGcDefault) Error() string {
	return fmt.Sprintf("[POST /app/rest/debug/jvm/gc][%d] requestGc default ", o._statusCode)
}

func (o *RequestGcDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
