// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RequestFinalizationReader is a Reader for the RequestFinalization structure.
type RequestFinalizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestFinalizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewRequestFinalizationDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewRequestFinalizationDefault creates a RequestFinalizationDefault with default headers values
func NewRequestFinalizationDefault(code int) *RequestFinalizationDefault {
	return &RequestFinalizationDefault{
		_statusCode: code,
	}
}

/*RequestFinalizationDefault handles this case with default header values.

successful operation
*/
type RequestFinalizationDefault struct {
	_statusCode int
}

// Code gets the status code for the request finalization default response
func (o *RequestFinalizationDefault) Code() int {
	return o._statusCode
}

func (o *RequestFinalizationDefault) Error() string {
	return fmt.Sprintf("[POST /app/rest/debug/jvm/finalization][%d] requestFinalization default ", o._statusCode)
}

func (o *RequestFinalizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
