// Code generated by go-swagger; DO NOT EDIT.

package test_occurrence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new test occurrence API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for test occurrence API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetTestOccurrences(params *GetTestOccurrencesParams, authInfo runtime.ClientAuthInfoWriter) (*GetTestOccurrencesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetTestOccurrences get test occurrences API
*/
func (a *Client) GetTestOccurrences(params *GetTestOccurrencesParams, authInfo runtime.ClientAuthInfoWriter) (*GetTestOccurrencesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTestOccurrencesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTestOccurrences",
		Method:             "GET",
		PathPattern:        "/app/rest/testOccurrences",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetTestOccurrencesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTestOccurrencesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getTestOccurrences: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
