// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ServeAPIVersion(params *ServeAPIVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ServeAPIVersionOK, error)

	ServeBuildFieldShort(params *ServeBuildFieldShortParams, authInfo runtime.ClientAuthInfoWriter) (*ServeBuildFieldShortOK, error)

	ServePluginInfo(params *ServePluginInfoParams, authInfo runtime.ClientAuthInfoWriter) (*ServePluginInfoOK, error)

	ServeVersion(params *ServeVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ServeVersionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ServeAPIVersion serve Api version API
*/
func (a *Client) ServeAPIVersion(params *ServeAPIVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ServeAPIVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServeAPIVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "serveApiVersion",
		Method:             "GET",
		PathPattern:        "/app/rest/apiVersion",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServeAPIVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ServeAPIVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for serveApiVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ServeBuildFieldShort serve build field short API
*/
func (a *Client) ServeBuildFieldShort(params *ServeBuildFieldShortParams, authInfo runtime.ClientAuthInfoWriter) (*ServeBuildFieldShortOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServeBuildFieldShortParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "serveBuildFieldShort",
		Method:             "GET",
		PathPattern:        "/app/rest/{projectLocator}/{btLocator}/{buildLocator}/{field}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServeBuildFieldShortReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ServeBuildFieldShortOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for serveBuildFieldShort: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ServePluginInfo serve plugin info API
*/
func (a *Client) ServePluginInfo(params *ServePluginInfoParams, authInfo runtime.ClientAuthInfoWriter) (*ServePluginInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServePluginInfoParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "servePluginInfo",
		Method:             "GET",
		PathPattern:        "/app/rest/info",
		ProducesMediaTypes: []string{"application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServePluginInfoReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ServePluginInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for servePluginInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ServeVersion serve version API
*/
func (a *Client) ServeVersion(params *ServeVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ServeVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServeVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "serveVersion",
		Method:             "GET",
		PathPattern:        "/app/rest/version",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServeVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ServeVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for serveVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
