// Code generated by go-swagger; DO NOT EDIT.

package federation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new federation API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for federation API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	AddServer(params *AddServerParams, authInfo runtime.ClientAuthInfoWriter) (*AddServerOK, error)

	Servers(params *ServersParams, authInfo runtime.ClientAuthInfoWriter) (*ServersOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  AddServer add server API
*/
func (a *Client) AddServer(params *AddServerParams, authInfo runtime.ClientAuthInfoWriter) (*AddServerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddServerParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addServer",
		Method:             "PUT",
		PathPattern:        "/app/rest/federation/servers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddServerReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddServerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for addServer: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Servers servers API
*/
func (a *Client) Servers(params *ServersParams, authInfo runtime.ClientAuthInfoWriter) (*ServersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "servers",
		Method:             "GET",
		PathPattern:        "/app/rest/federation/servers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ServersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for servers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
