// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricTags metric tags
//
// swagger:model metricTags
type MetricTags struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// metric tag
	MetricTag []*MetricTag `json:"metricTag"`
}

// Validate validates this metric tags
func (m *MetricTags) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetricTag(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricTags) validateMetricTag(formats strfmt.Registry) error {

	if swag.IsZero(m.MetricTag) { // not required
		return nil
	}

	for i := 0; i < len(m.MetricTag); i++ {
		if swag.IsZero(m.MetricTag[i]) { // not required
			continue
		}

		if m.MetricTag[i] != nil {
			if err := m.MetricTag[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metricTag" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricTags) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricTags) UnmarshalBinary(b []byte) error {
	var res MetricTags
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
