// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricTag metric tag
//
// swagger:model metricTag
type MetricTag struct {

	// name
	Name string `json:"name,omitempty" xml:"name"`

	// value
	Value string `json:"value,omitempty" xml:"value"`
}

// Validate validates this metric tag
func (m *MetricTag) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricTag) UnmarshalBinary(b []byte) error {
	var res MetricTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
