// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParsedTestName parsed test name
//
// swagger:model ParsedTestName
type ParsedTestName struct {

	// test class
	TestClass string `json:"testClass,omitempty" xml:"testClass"`

	// test method name
	TestMethodName string `json:"testMethodName,omitempty" xml:"testMethodName"`

	// test name with parameters
	TestNameWithParameters string `json:"testNameWithParameters,omitempty" xml:"testNameWithParameters"`

	// test name without prefix
	TestNameWithoutPrefix string `json:"testNameWithoutPrefix,omitempty" xml:"testNameWithoutPrefix"`

	// test package
	TestPackage string `json:"testPackage,omitempty" xml:"testPackage"`

	// test short name
	TestShortName string `json:"testShortName,omitempty" xml:"testShortName"`

	// test suite
	TestSuite string `json:"testSuite,omitempty" xml:"testSuite"`
}

// Validate validates this parsed test name
func (m *ParsedTestName) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParsedTestName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParsedTestName) UnmarshalBinary(b []byte) error {
	var res ParsedTestName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
